Route7_Text_UndergroundPathSign:: @ 8184097
    .string "{UP_ARROW} LAVENDER TOWN (VIA UG PATH)\n"
    .string "{LEFT_ARROW} CELADON CITY (VIA ROUTE 7)\l"
    .string "{RIGHT_ARROW} SAFFRON CITY (VIA GATEHOUSE)\p"
    .string "CURRENT LOCATION:\n"
    .string "ROUTE 7$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
    .string "I sometimes watch wild POKéMON\n"
    .string "gather BERRIES and leave them\l"
    .string "around spots like this!\p"
    .string "Here you go!\n"
    .string "You can have this one!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
    .string "I'm going to try really hard to find\n"
    .string "BERRIES in different colors.\p"
    .string "I hope you try hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
    .string "I wonder what color BERRIES I'll look\n"
    .string "for today?$"