ViridianCity_Mart_Text_YouCameFromPallet:: @ 819021A
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak:: @ 819023A
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk:: @ 8190289
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_HaveTheseAsThanks:: @ 819023A
    .string "You can have the last of our two\n"
    .string "most popular items for your efforts.$"

ViridianCity_Mart_Text_ReceivedBerryPouchFromClerk:: @ 8190289
    .string "{PLAYER} received the BERRY POUCH\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_ReceivedTMCaseFromClerk:: @ 8190289
    .string "{PLAYER} received the TM CASE\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe:: @ 81902BF
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes:: @ 81902F5
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions:: @ 819032C
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"

